name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
    TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    permissions:
      pages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: |
          node src/controllers/githubApi.ts

      - name: Set Git remote URL
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: GitHub Config
        run: |
              git config --global user.email "lane7520@gmail.com"
              git config --global user.name "jonolane"

      - name: Deploy to GitHub Pages
        run: npm run deploy -u "github-actions-bot <support+actions@github.com>"